allowBuilds:
  '@reown/appkit': true
  bigint-buffer: true
  bufferutil: true
  protobufjs: true
  sharp: false
  unrs-resolver: false
  utf-8-validate: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@dynamic-labs-wallet/core@1.0.38'
  - '@dynamic-labs-wallet/node-evm@1.0.38'
  - '@dynamic-labs-wallet/node@1.0.38'
  - '@dynamic-labs-wallet/primitives@1.0.38'
